name: VPS Setup - Direct SSH
on:
  workflow_dispatch:

env:
  SSH_PASSWORD: "root@123"

jobs:
  secure-vps:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    
    steps:
    - name: Install & Secure SSH
      run: |
        sudo apt update -y
        sudo apt install -y openssh-server ufail2ban
        
        # تأمين SSH
        echo "root:$SSH_PASSWORD" | sudo chpasswd
        echo "PermitRootLogin yes" >> /etc/ssh/sshd_config
        echo "PasswordAuthentication yes" >> /etc/ssh/sshd_config
        echo "ClientAliveInterval 60" >> /etc/ssh/sshd_config
        
        # فتح port SSH
        sudo ufw allow 22/tcp
        sudo ufw --force enable
        
        sudo systemctl restart ssh
        echo "SSH secured and running"

    - name: Display Connection Info
      run: |
        PUBLIC_IP=$(curl -s ifconfig.me)
        echo "=========================================="
        echo "VPS READY FOR SSH CONNECTION"
        echo "Public IP: $PUBLIC_IP"
        echo "Port: 22"
        echo "Username: root"
        echo "Password: $SSH_PASSWORD"
        echo "=========================================="
        echo "Connect using:"
        echo "ssh root@$PUBLIC_IP"
        echo "=========================================="

    - name: Keep VPS Alive
      run: |
        # نسخة محسنة مع معالجة الإشارات
        cleanup() {
            echo "[$(date)] Cleaning up before exit..."
            exit 0
        }
        trap cleanup SIGTERM SIGINT
        
        while true; do
            echo "[$(date)] VPS running - IP: $(curl -s ifconfig.me)"
            sleep 300
        done
